# Generated by Django 3.0.1 on 2021-03-12 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('classapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdefinition',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='staff.Staff', verbose_name='Teacher'),
        ),
        migrations.AddField(
            model_name='classdefinition',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='classapp.Subject', verbose_name='subject'),
        ),
    ]
