# Generated by Django 3.1.7 on 2021-03-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0002_auto_20210312_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classdefinition',
            name='weekday',
        ),
        migrations.AlterField(
            model_name='classdefinition',
            name='class_date',
            field=models.DateField(blank=True, null=True, verbose_name='Class date'),
        ),
    ]
