# Generated by Django 3.1.7 on 2021-03-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0003_auto_20210313_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdefinition',
            name='class_date',
            field=models.DateField(null=True, verbose_name='Class date'),
        ),
        migrations.AlterField(
            model_name='classdefinition',
            name='class_status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('cancelled', 'cancelled')], default='scheduled', max_length=200, verbose_name='Class status'),
        ),
        migrations.AlterField(
            model_name='classdefinition',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='classdefinition',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Start time'),
        ),
    ]
