# Generated by Django 3.1.7 on 2021-03-14 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_studentinclass_class_id'),
        ('classapp', '0004_auto_20210313_2356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassDefinition',
        ),
    ]
