# Generated by Django 3.0.1 on 2021-03-12 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cell_phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('street', models.CharField(max_length=200, null=True, verbose_name='Street')),
                ('city', models.CharField(max_length=200, null=True, verbose_name='City')),
                ('zip', models.CharField(max_length=20, null=True, verbose_name='Zip code')),
                ('joining_date', models.DateField(null=True, verbose_name='joining date')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Date of birth')),
                ('photo', models.TextField(blank=True, null=True, verbose_name='Photo')),
                ('subjects', models.ManyToManyField(related_name='staff_subjects', to='classapp.Subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
