# Generated by Django 3.1.7 on 2021-03-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20210313_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='city',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='street',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='zip',
        ),
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
    ]
