# Generated by Django 3.1.7 on 2021-03-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0002_auto_20210312_1933'),
        ('staff', '0004_auto_20210313_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='cell_phone',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='staff',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='staff_subjects', to='classapp.Subject'),
        ),
    ]
