# Generated by Django 3.0.1 on 2021-03-12 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('phone', models.CharField(max_length=20, verbose_name='Cell phone')),
                ('photo', models.TextField(blank=True, null=True, verbose_name='Photo')),
                ('street', models.CharField(blank=True, max_length=200, null=True, verbose_name='Street')),
                ('street_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Second Street')),
                ('country', models.CharField(blank=True, max_length=200, null=True, verbose_name='country')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=200, null=True, verbose_name='State')),
                ('zip', models.CharField(blank=True, max_length=30, null=True, verbose_name='Zip code')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_name', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentInClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('comments', models.TextField(max_length=200, null=True)),
                ('class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classapp.ClassDefinition')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_in_class_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_in_class_modified_by', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_student', to='student.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
