# Generated by Django 3.1.7 on 2021-03-14 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210313_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinclass',
            name='class_id',
        ),
    ]
