# Generated by Django 3.1.7 on 2021-03-14 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0006_classdefinition'),
        ('student', '0004_remove_studentinclass_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinclass',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classapp.classdefinition'),
        ),
    ]
